create extension if not exists citext;

create table if not exists public.app_users (
    id bigint generated by default as identity primary key,
    email citext not null unique,
    hashed_password varchar(255) not null,
    full_name varchar(120) not null,
    role varchar(20) not null check (role in ('patient', 'provider', 'admin')),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.provider_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.app_users(id),
    display_name varchar(120) not null,
    provider_type varchar(80) not null default 'therapist',
    credential varchar(80),
    profile_photo_url varchar(500),
    quote text not null default '',
    bio text not null default '',
    city varchar(80) not null,
    state varchar(40) not null,
    timezone varchar(80) not null default 'America/New_York',
    years_experience integer,
    gender varchar(80),
    ethnicity varchar(120),
    languages jsonb not null default '[]'::jsonb,
    license_states jsonb not null default '[]'::jsonb,
    offers_virtual boolean not null default true,
    offers_in_person boolean not null default false,
    offers_free_consultation boolean not null default false,
    accepting_new_clients boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_provider_years_experience
        check (years_experience is null or years_experience between 0 and 80)
);

create table if not exists public.specialties (
    id bigint generated by default as identity primary key,
    name varchar(80) not null unique
);

create table if not exists public.provider_specialties (
    provider_id bigint not null references public.provider_profiles(id),
    specialty_id bigint not null references public.specialties(id),
    primary key (provider_id, specialty_id)
);

create table if not exists public.style_tags (
    id bigint generated by default as identity primary key,
    name varchar(80) not null unique
);

create table if not exists public.provider_style_tags (
    provider_id bigint not null references public.provider_profiles(id),
    style_tag_id bigint not null references public.style_tags(id),
    primary key (provider_id, style_tag_id)
);

create table if not exists public.care_types (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique
);

create table if not exists public.provider_care_types (
    provider_id bigint not null references public.provider_profiles(id),
    care_type_id bigint not null references public.care_types(id),
    primary key (provider_id, care_type_id)
);

create table if not exists public.insurance_plans (
    id bigint generated by default as identity primary key,
    carrier_name varchar(100) not null,
    plan_name varchar(100) not null,
    display_name varchar(160) not null,
    constraint uq_insurance_carrier_plan unique (carrier_name, plan_name)
);

create table if not exists public.patient_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.app_users(id),
    preferred_name varchar(120),
    legal_name varchar(120),
    pronouns varchar(80),
    phone varchar(40),
    gender varchar(80),
    gender_status varchar(80),
    ethnicity varchar(120),
    language varchar(80),
    insurance_plan_id bigint references public.insurance_plans(id),
    two_factor_enrolled boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.patient_addresses (
    id bigint generated by default as identity primary key,
    patient_id bigint not null references public.app_users(id),
    label varchar(40) not null default 'home',
    line1 varchar(160) not null,
    line2 varchar(160),
    city varchar(80) not null,
    state varchar(40) not null,
    postal_code varchar(20) not null,
    country varchar(2) not null default 'US',
    source varchar(40) not null default 'self_reported'
        check (source in ('self_reported', 'insurance', 'provider', 'imported')),
    is_primary boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.emergency_contacts (
    id bigint generated by default as identity primary key,
    patient_id bigint not null references public.app_users(id),
    full_name varchar(120) not null,
    relationship varchar(80),
    phone varchar(40) not null,
    email citext,
    priority integer not null default 1 check (priority between 1 and 2),
    permission_to_contact boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_emergency_contact_priority unique (patient_id, priority)
);

create table if not exists public.consent_forms (
    id bigint generated by default as identity primary key,
    form_key varchar(80) not null unique,
    title varchar(160) not null,
    version varchar(40) not null,
    body_url varchar(500),
    is_required boolean not null default true,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.patient_consent_acknowledgements (
    id bigint generated by default as identity primary key,
    patient_id bigint not null references public.app_users(id),
    consent_form_id bigint not null references public.consent_forms(id),
    form_version varchar(40) not null,
    accepted_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_patient_consent_acknowledgement unique (patient_id, consent_form_id)
);

create table if not exists public.provider_insurance_plans (
    provider_id bigint not null references public.provider_profiles(id),
    insurance_plan_id bigint not null references public.insurance_plans(id),
    primary key (provider_id, insurance_plan_id)
);

create table if not exists public.availability_slots (
    id bigint generated by default as identity primary key,
    provider_id bigint not null references public.provider_profiles(id),
    start_at timestamptz not null,
    end_at timestamptz not null,
    status varchar(20) not null default 'open' check (status in ('open', 'booked', 'cancelled')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_slots_end_after_start check (end_at > start_at),
    constraint uq_provider_slot_time unique (provider_id, start_at, end_at)
);

create table if not exists public.appointment_requests (
    id bigint generated by default as identity primary key,
    patient_id bigint not null references public.app_users(id),
    provider_id bigint not null references public.provider_profiles(id),
    slot_id bigint not null references public.availability_slots(id),
    status varchar(20) not null default 'pending'
        check (status in ('pending', 'confirmed', 'declined', 'cancelled', 'completed')),
    reason text,
    cancelled_reason text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.slot_watchers (
    id bigint generated by default as identity primary key,
    patient_id bigint not null references public.app_users(id),
    provider_id bigint not null references public.provider_profiles(id),
    start_after timestamptz not null,
    start_before timestamptz not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_watchers_valid_window check (start_before > start_after)
);

create table if not exists public.provider_follows (
    id bigint generated by default as identity primary key,
    patient_id bigint not null references public.app_users(id),
    provider_id bigint not null references public.provider_profiles(id),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.app_users(id),
    slot_id bigint not null references public.availability_slots(id),
    appointment_request_id bigint references public.appointment_requests(id),
    type varchar(40) not null check (type in ('slot_opened', 'slot_reopened')),
    message text not null,
    is_read boolean not null default false,
    created_at timestamptz not null default now(),
    read_at timestamptz
);

create table if not exists public.outbox_events (
    id bigint generated by default as identity primary key,
    event_type varchar(80) not null,
    aggregate_type varchar(80) not null,
    aggregate_id bigint not null,
    user_id bigint not null references public.app_users(id),
    payload jsonb not null,
    status varchar(20) not null default 'pending'
        check (status in ('pending', 'published', 'failed')),
    attempt_count integer not null default 0,
    stream_message_id varchar(80),
    last_error text,
    created_at timestamptz not null default now(),
    published_at timestamptz
);

create index if not exists ix_app_users_email on public.app_users(email);
create index if not exists ix_provider_profiles_city_state on public.provider_profiles(city, state);
create index if not exists ix_provider_profiles_offers_virtual on public.provider_profiles(offers_virtual);
create index if not exists ix_provider_profiles_offers_in_person on public.provider_profiles(offers_in_person);
create index if not exists ix_provider_profiles_provider_type on public.provider_profiles(provider_type);
create index if not exists ix_provider_profiles_gender on public.provider_profiles(gender);
create index if not exists ix_provider_profiles_ethnicity on public.provider_profiles(ethnicity);
create index if not exists ix_provider_profiles_accepting on public.provider_profiles(accepting_new_clients);
create index if not exists ix_provider_specialties_specialty
    on public.provider_specialties(specialty_id);
create index if not exists ix_provider_style_tags_style
    on public.provider_style_tags(style_tag_id);
create index if not exists ix_provider_care_types_care
    on public.provider_care_types(care_type_id);
create index if not exists ix_provider_insurance_plans_plan
    on public.provider_insurance_plans(insurance_plan_id);
create index if not exists ix_patient_profiles_insurance_plan
    on public.patient_profiles(insurance_plan_id);
create index if not exists ix_patient_addresses_patient
    on public.patient_addresses(patient_id);
create unique index if not exists uq_patient_primary_address
    on public.patient_addresses(patient_id)
    where is_primary = true;
create index if not exists ix_emergency_contacts_patient
    on public.emergency_contacts(patient_id);
create index if not exists ix_consent_forms_active_required
    on public.consent_forms(is_active, is_required);
create index if not exists ix_patient_consents_patient_accepted
    on public.patient_consent_acknowledgements(patient_id, accepted_at);
create index if not exists ix_slots_provider_status_start
    on public.availability_slots(provider_id, status, start_at);
create index if not exists ix_appointments_patient_status
    on public.appointment_requests(patient_id, status);
create index if not exists ix_appointments_provider_status
    on public.appointment_requests(provider_id, status);
create index if not exists ix_appointments_slot on public.appointment_requests(slot_id);
create unique index if not exists uq_active_appointment_per_slot
    on public.appointment_requests(slot_id)
    where status in ('pending', 'confirmed');
create index if not exists ix_watchers_patient on public.slot_watchers(patient_id);
create index if not exists ix_watchers_provider_active on public.slot_watchers(provider_id, is_active);
create unique index if not exists uq_active_watcher_window
    on public.slot_watchers(patient_id, provider_id, start_after, start_before)
    where is_active = true;
create index if not exists ix_provider_follows_patient
    on public.provider_follows(patient_id);
create index if not exists ix_provider_follows_provider_active
    on public.provider_follows(provider_id, is_active);
create unique index if not exists uq_active_provider_follow
    on public.provider_follows(patient_id, provider_id)
    where is_active = true;
create index if not exists ix_notifications_user_read_created
    on public.notifications(user_id, is_read, created_at);
create unique index if not exists uq_notification_dedupe
    on public.notifications(user_id, slot_id, appointment_request_id, type)
    where appointment_request_id is not null;
create unique index if not exists uq_notification_slot_event_dedupe
    on public.notifications(user_id, slot_id, type)
    where appointment_request_id is null;
create index if not exists ix_outbox_status_created
    on public.outbox_events(status, created_at);
create index if not exists ix_outbox_user_created
    on public.outbox_events(user_id, created_at);

alter table public.app_users enable row level security;
alter table public.patient_profiles enable row level security;
alter table public.patient_addresses enable row level security;
alter table public.emergency_contacts enable row level security;
alter table public.consent_forms enable row level security;
alter table public.patient_consent_acknowledgements enable row level security;
alter table public.provider_profiles enable row level security;
alter table public.specialties enable row level security;
alter table public.provider_specialties enable row level security;
alter table public.style_tags enable row level security;
alter table public.provider_style_tags enable row level security;
alter table public.care_types enable row level security;
alter table public.provider_care_types enable row level security;
alter table public.insurance_plans enable row level security;
alter table public.provider_insurance_plans enable row level security;
alter table public.availability_slots enable row level security;
alter table public.appointment_requests enable row level security;
alter table public.slot_watchers enable row level security;
alter table public.provider_follows enable row level security;
alter table public.notifications enable row level security;
alter table public.outbox_events enable row level security;
